### ISSUE TITLE
Compilation Error in Visual Studio

### ISSUE THREAD

**Issue by hokching** [EmmanuelAsmFun/asmfun#1]
Hi, I've opened the source in Visual Studio 2019 community, and got many errors

Have you committed the latest source to the repo?

**Comment by EmmanuelAsmFun** [comment]
Oh, I see merge mistakes. Gonne fix them. Thanks for notification!

**Comment by hokching** [comment]
actually, I downloaded the code in order to look at problem #2

**Comment by EmmanuelAsmFun** [comment]
Ok fixt. It seems that the WPF version has a bug due to a new .net core version. SDL version works good.

**Comment by EmmanuelAsmFun** [comment]
Is it working? @hokching

**Comment by hokching** [comment]
Awesome, I'll try it tomorrow, thx!

**Comment by hokching** [comment]
The solution projects compiled without issues now, thx
but I still encounter problems, e.g. #4

**Comment by hokching** [comment]
I suggest you download the source from Github yourself and test it

**Comment by hokching** [comment]
Also, the redistributed download binary seems not working (https://asmfun.com/downloads/ASMFunWindows.zip)
I actually found the binary to be not working at first, and that's why I downloaded the source code to check the problem

**Comment by EmmanuelAsmFun** [comment]
@hokching I just updated the windows zip and added an embedded ide in nw.js . Now it's much easier to use. So the browser pages gets loaded through nw.js exe app.
The downloaded is started when we click on the Launch IDE in the console.
