### ISSUE TITLE
locahost:5001 not working + Cannot start local IDE

### ISSUE THREAD

**Issue by hokching** [EmmanuelAsmFun/asmfun#2]
I run ASMFunPlayer.exe, and when I choose "launch local IDE", the browser window browses localhost:5001, and said "no web page found"

**Comment by EmmanuelAsmFun** [comment]
Can you try the online version?
https://asmfun.com/for-commander-x16/

The local version, you have to run 
http://localhost:5001/for-commander-x16/

**Comment by EmmanuelAsmFun** [comment]
Don't forget to compile the front end
Code\Src\Ide\AsmFun.BrowserPages\tsc
install typescript correct version if needed
npm install typescript@3.9.5 -g

**Comment by hokching** [comment]
Ok I am able to see stuffs in http://localhost:5001/for-commander-x16/index.html
but still got the sdl2 error (#4)
