### ISSUE TITLE
Can't launch any sample projects using the online IDE

### ISSUE THREAD

**Issue by hokching** [EmmanuelAsmFun/asmfun#3]
The source code did load, but I can't get it running in x16emu even if I tried and tried

**Comment by hokching** [comment]
The project I tried to load:
Thrawn's snake game
![image](https://user-images.githubusercontent.com/10129190/113476710-bada7a00-94af-11eb-82b4-78ec6d157ae5.png)

**Comment by hokching** [comment]
at least please guide me how to properly run a hello world sample project or something ?

**Comment by EmmanuelAsmFun** [comment]
It is fixt
