### ISSUE TITLE
Online IDE: Unable to load DLL 'SDL2' or one of its dependencies

### ISSUE THREAD

**Issue by hokching** [EmmanuelAsmFun/asmfun#4]
: 'Unable to load DLL 'SDL2' or one of its dependencies: The specified module could not be found. (0x8007007E)'

Steps to reproduce error:
Startup project: AsmFun.SDL2
Launch Online IDE
open sample project
Run sample project

**Comment by EmmanuelAsmFun** [comment]
You have to extract the zip file lib/SDLWindows64Dll.zip to your build folder. This is for a 64bit machine. If you have a 32bit, you'll have to download it from https://www.libsdl.org/download-2.0.php
